name: Build
run-name: "Build: ${{ github.head_ref || github.ref_name }}"

on:
  push:
    branches:
    - main
  pull_request:

jobs:
  build:
    name: Build
    runs-on: ubuntu-latest
    steps:
      - name: Checkout the repository
        uses: actions/checkout@v4

      - name: Setup cmake
        uses: jwlawson/actions-setup-cmake@v2
        with:
          cmake-version: '3.29.x'

      - name: Install ninja
        uses: seanmiddleditch/gha-setup-ninja@v5

      - name: Vcpkg
        id: vcpkg
        uses: johnwason/vcpkg-action@v6
        with:
          manifest-dir: ${{ github.workspace }}
          triplet: x64-linux
          revision: master
          token: ${{ github.token }}
          github-binarycache: true
          fetch-depth: 0

      - name: Build g++
        uses: ./.github/actions/build
        with:
          cxx: g++
          config: Release
          build-dir: out/g++-release
          install: ${{ github.workspace }}/out/install

      - name: Build clang++
        uses: ./.github/actions/build
        with:
          cxx: clang++
          config: Debug
          build-dir: out/clang++-debug
          cmake-args: -DCMAKE_EXPORT_COMPILE_COMMANDS=ON

      - name: Build clang++ (no protobuf)
        uses: ./.github/actions/build
        with:
          cxx: clang++
          config: Debug
          build-dir: out/clang++-release-noproto
          cmake-args: -DSCHEMATIC_PROTOBUF=OFF

      - name: Lint changes
        uses: cpp-linter/cpp-linter-action@v2.12.1
        id: linter
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          style: file
          files-changed-only: true
          tidy-checks: ''
          version: 18
          verbosity: 20
          ignore: out|vcpkg
          database: out/clang++debug
          extra-args: -std=c++23
          step-summary: true

      - name: Lint fail check
        if: ${{ steps.linter.outputs.checks-failed != 0}}
        run: |
          echo "Some linter checks failed. (${{ steps.linter.outputs.checks-failed }})"
          exit 1
