name: Build
run-name: "Build: ${{ github.head_ref || github.ref_name }}"

on:
  push:
    branches:
    - main
  pull_request:

jobs:
  build-project:
    name: Ubuntu GCC
    runs-on: ubuntu-latest
    steps:
      - name: Checkout the repository
        uses: actions/checkout@v4

      - name: Setup cmake
        uses: jwlawson/actions-setup-cmake@v2
        with:
          cmake-version: '3.26.x'

      - name: Install ninja
        uses: seanmiddleditch/gha-setup-ninja@v5

      - name: Vcpkg
        id: vcpkg
        uses: seanmiddleditch/vcpkg-action@master
        with:
          manifest-dir: ${{ github.workspace }}
          triplet: x64-linux
          revision: master
          token: ${{ github.token }}

      - name: Set environment
        run: |
          echo "BUILD=out/build/linux-debug" | tee -a "$GITHUB_ENV"

      - name: Configure the project
        run: |
          mkdir out
          cmake -G Ninja --preset linux-debug ${{ steps.vcpkg.outputs.vcpkg-cmake-config }}

      - name: Build the project
        run: cmake --build ${BUILD}

      - name: Test the project
        run: ctest --no-tests=error --output-on-failure --test-dir ${BUILD}

      - name: Install the project
        run: cmake --install ${BUILD}

      - name: Lint changes
        uses: cpp-linter/cpp-linter-action@v2.6.1
        id: linter
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          style: file
          files-changed-only: true
          tidy-checks: ''
          version: 18
          verbosity: 20
          ignore: out|vcpkg
          database: ${{ env.BUILD }}
          step-summary: true

      - name: Lint fail check
        if: ${{ steps.linter.outputs.checks-failed != 0}}
        run: |
          echo "Some linter checks failed. (${{ steps.linter.outputs.checks-failed }})"
          exit 1
